# Generated by Django 6.1 on 2026-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
